### ISSUE TITLE
Preliminary review of view code.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-pairs#20]
Similar to the model review that I did in https://github.com/phetsims/number-pairs/issues/9#issuecomment-2375275553 ...

Most of the view code is in number-pairs/common/view/.

Focus on these classes first:
* CubesOnWireNode
* NumberLineNode
* NumberLineSlider

**Comment by pixelzoom** [comment]
@marlitas The view is looking really great - some nice solutions to complicated problems. Well done!

Here a check list of things thast I noted.  I'm going to add to this list as I go, and will assign to you to review when I'm done. Let me know if you'd like to discuss any of these.

- [ ] CubesOnWireNode: Say something in the header doc about the implications of the cubes being on a wire. Because they are on a wire, dragging a cube left/right also moves the other cubes to its left/right.  (You may recall that this is a distinction that I didn’t pick up on immediately. :)

- [ ] CubesOnWireNode: Duplicate code for creating `wireMinXEndCap` and `wireMaxXEndCap`. Create inner `class EndCap extends Path`.

- [ ] CubesOnWireNode: `snapCubesToPositions` and `handleCubeMove` should be private.

- [ ] CubesOnWireNode: `calculateCubeSeparatorPlacement` does not need to be a class method.  It could be a function outside the class definition.

- [ ] NumberLineNode: `superOptions` is misleading because it’s not just the options for the superclass, it also includes SelfOptions. It’s also not the convention for the PhET Options pattern. Rename to `options`.

- [ ] NumberLineNode: As I understand it `zeroNumberProperty` should always be 0. This would be a bit safer:

```diff
// EllipticalArrowNode needs the starting and ending values to be Property<number> instances. Even though
// the starting value for the leftAddendArrow and totalArrow will always be 0.
- const zeroNumberProperty = new Property( options.numberLineRange.min );
+ const zeroNumberProperty = new Property( options.numberLineRange.min, {
+   isValidValue: value => value === options.numberLineRange.min
+ } );
```

- [ ] There are many misuses of `combineOptions`. For example, see CubeNode. The type of `providedOptions` is CubeNodeOptions, and `optionize` should be used instead of combineOptions.

```diff
- const options = combineOptions<NodeOptions>( {
+ const options = optionize<CubeNodeOptions, SelfOptions, NodeOptions>()( {
  children: [ cubeLeftAddendImage, cubeRightAddendImage ],
  visibleProperty: new DerivedProperty( [ model.addendTypeProperty ], addendType => addendType !== AddendType.INACTIVE )
}, providedOptions );
```

There are similar misuses of combineOptions in:

* CubesOnWireNode:
* EllipticalArrowNode: 
* KittenNode
* KittenLayerNode:
* LocationCountingObjectNode:
* NumberBondNode
* NumberCircle
* NumberLineNode
* NumberLineOptionsCheckboxGroup
* NumberLineSlider

**Comment by pixelzoom** [comment]
Review completed, over to you @marlitas.

**Comment by marlitas** [comment]
> You may also wish to exclude NodeTranslationOptions if this class is really responsive for translation.

I would like those translation options to be the default, but I don't think passing in a different translation in a non-default use case would break the component.

-  I have a question about options pattern that I documented with this issue number in KittenNode

> Valid values for countingRepresentationTypeProperty should be obtained from that Property.

This is an option because each screen has a different set of counting representation types. I can't determine that based on valid values. Perhaps an assertion to confirm that any values I pass in are of CountingRepresentationType. But I thought that would be covered by type checking with the option's type defined as: `CountingRepresentationType[]`. Or wait... perhaps you're indicating that the valid values for that Property are specifically defined for each screen? Let's confirm I'm understanding on Monday.

**Comment by pixelzoom** [comment]
> Or wait... perhaps you're indicating that the valid values for that Property are specifically defined for each screen?

Correct. The default for validValues in this case is CountingRepresentationType.enumeration.values.  That is not appropriate for all screens -- validValues should be a subset of CountingRepresentationType.enumeration.values.  Otherwise you (or a PhET-iO client!) can set countingRepresentationTypeProperty to a value that is not supported by a screen.

**Comment by marlitas** [comment]
I believe all of the items in this issue have been addressed. @pixelzoom feel free to re-open if you disagree.
