### ISSUE TITLE
Swap out cube and kitten .svg

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/number-pairs#24]
I noticed the cubes looked blurry, so I asked AM about it. She said the .svgs were much too big, so I re-exported to be smaller. 

In the 'assets' folder, there are new .svgs with a 'small' included in the title that will hopefully make the kittens and cubes look brighter and more defined. Hopefully it helps.

**Comment by catherinecarter** [comment]
Cube svgs will be replaced with a bead that @amanda-phet is creating.

**Comment by marlitas** [comment]
This is no longer relevant now that we changed to beads
