### ISSUE TITLE
Pixel polishes part deux

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/number-pairs#30]
Some pixel polishes for brain breaks :)

- [x] Increase stroke on circles in number bond
- [x] Increase size of scene selection buttons (numbers)
- [x] Change fill color of scene selection buttons to match the color at the top of the number bond
- [x] Starting state for accordion boxes
   - [x] Intro screen: sentence closed, number bond open
   - [x] Ten screen: sentence and equation closed, number bond open
   - [x] Twenty screen: sentence and equation closed, number bond open
   - [x] Sum: sentence closed, equation and number bond open
- [x] Remove stroke on word highlights 
   <img width="348" alt="image" src="https://github.com/user-attachments/assets/6943d9d1-c4c9-4e26-920b-47f52fd28abb">
- [ ] Center the number bond in the accordion box (looks like it's centered between the right edge of the accordion box and the right edge of the collapse button. For the sum screen, we might have to make the bond lines shorter to accommodate the centering, or we might have to brainstorm ideas for that panel
   <img width="254" alt="image" src="https://github.com/user-attachments/assets/a079756e-cb33-4043-a280-87200406982f">  <img width="252" alt="image" src="https://github.com/user-attachments/assets/82207654-346b-4ef0-8603-cbc8fc4387e4">

**Comment by marlitas** [comment]
> Increase size of scene selection buttons (numbers)

I wasn't able to increase this to be the same size as the ten frame and commutative buttons. Doing so would have cause the radio buttons to expand past the edge of the screen vertically.

**Comment by marlitas** [comment]
All the above have been addressed except for: 
`Center the number bond in the accordion box`

I think this is a larger design question about how we want items in an accordion box to appear if there is no title content when expanded. CC is correct that the accordion box logic has the content center between the button and the right edge. This could be addressed in a hacky work around way, but begs the question is the common code component doing what we actually want? Another option that works with what common code already supports is showing the title when the accordion box is expanded. We would need to make the number bond smaller but would be centered like so:

<img width="478" alt="image" src="https://github.com/user-attachments/assets/704efd05-8789-4f6d-b948-6ecb3dff8b73">


Accordion Box is also in `sun` which @pixelzoom is the responsible dev for. I wonder if there's already history and context for this that he may have an opinion on.

**Comment by marlitas** [comment]
@catherinecarter and I talked about this during standup today. CC is okay with dropping the Number Bond down and making it smaller, but would like that to happen without the title being visible. 

One way I thought of doing this was by passing in a `ToggleNode` that switches between the title Text and an empty Node when the accordion box is expanded. I prefer this method to messing with the visibility of the title Text since `AccordionBox` is doing that already in an `expandedPropertyObserver`.  @pixelzoom does this feel okay? I know it's a bit hacky, but it feels like it might be on the line of acceptable hack.

**Comment by pixelzoom** [comment]
The workaround described in https://github.com/phetsims/number-pairs/issues/30#issuecomment-2528772186 is going to be a problem for description and PhET-iO.

Imo, I would leave things as-is, and not worry about the number bond being exactly centered. That is the unfortunate reality of AccordionBox.   If you think it's a big enough issue to go to the trouble of changing AccordionBox, then that's where the change should be made.

**Comment by catherinecarter** [comment]
To recap and make sure I'm understanding the options, here's what I'm reading (and my possible concerns about each option): 
1. Do nothing and accept that the number bond is non-centered. 
   * Concern: the only place this matters to me is for the location-based representations since the number bond and the left/right panels won't match up, potentially sending the message that one addend is more important than the other or some other unintended interpretation: 
   * <img width="305" alt="image" src="https://github.com/user-attachments/assets/139287d5-8671-43d9-a44a-48667afe20c1">

2. Keep the title visible no matter whether open or closed, then the number bond will be centered but smaller.
   * Concern: this would be the only accordion box out of the three whose title would stay visible when open. This might look strange and make users wonder why one accordion box has text while the others don't. If we kept text in all three, the equation accordion box will be too vertically tall, leaving not enough room for the checkboxes on number line representation.
   
3. Do a hacky workaround
   * Concern: CM advised against this
    
4. Modify the global functionality of the accordion box
   * I have no idea what this entails 

Did I capture those options correctly?

**Comment by pixelzoom** [comment]
Yes, https://github.com/phetsims/number-pairs/issues/30#issuecomment-2532813716 is a nice summary of the options.

**Comment by catherinecarter** [comment]
Ok, since I don't know the implications of option 4 (e.g., would other published sims be impacted?), if I had to choose right this moment, I'd choose option 2, unless option 4 isn't as intensive as it seems to be on the surface.

**Comment by marlitas** [comment]
@catherinecarter option 4 would be rather intensive and affect other sims. We would need larger approval from the team (both designers and developers (mainly JO)) to do that work as well.

I can move forward with option 2.

**Comment by pixelzoom** [comment]
My vote would be option 1.  Making the contents of the accordion box as large as possible seems more important than whether the content is centered in the accordion box.  There is plenty of horizontal space, but constrained vertical space, so option 2 will require making the contents smaller, which seems like a poor tradeoff for centering.

**Comment by catherinecarter** [comment]
@pixelzoom, I'm guessing the size of the circles probably won't change much, it will be the length of the lines going from the top circle to the bottom two circles. We'll have to see how it looks and how much the circle sizes change, but shortening the lines connecting can hopefully be the main target.

**Comment by marlitas** [comment]
Number bond has been updated above. I went over the changes with @catherinecarter for pixel polishing. @catherinecarter feel free to close if everything here is done.

**Comment by catherinecarter** [comment]
Number bond looks good. We discussed at the design meeting 12/12 and consensus was that option 2 (i.e. the title of Number Bond to center the bond) was the option most liked. Closing.
