### ISSUE TITLE
Increase width of spinners on Sum screen

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/number-pairs#34]
The images look tight in the spinner with the up/down arrows above and below. Let's make the width of the rectangle wider to the left (closer to the counting area). I wonder if making them the same width (not changing the height) of the yellow organize and commutative property buttons would make it look less cramped?

<img width="137" alt="image" src="https://github.com/user-attachments/assets/ff53a499-9453-470e-b6e7-c4eebfc0827e">

**Comment by marlitas** [comment]
Done above. Over to @catherinecarter for review.

**Comment by catherinecarter** [comment]
Looks good to me. Thanks!
