### ISSUE TITLE
Maintain which kitten is blue?

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/number-pairs#35]
When I was playing with the Sum screen, I was adding new yellow kittens to change the left addend. I noticed that the blue kitten was moving around, i.e. the current blue kitten changed to yellow to represent the new yellow kitten, and therefore the new kitten physically added to the counting area changed to be blue. 

This gave the impression that two new kittens were being added. 
Here's with seven kittens: 
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/8160c9d5-fdbf-4178-973e-00a4179835ea">

Adding one more: 
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/d243a8a4-d940-4ca8-8024-9338e02d24bc">

Can we keep the currently numbered blue kitten to stay its color, and any new kittens added become the "next" number in line? It feels distracting to have two things change at the same time: the number of kittens of that color, and the color of a kitten.

This would also hold true when removing the kittens. So if the kittens are numbered like below (so they're not in numerical order per addend): 

And I take away a yellow kitten, the first one to be removed would be either 2 or 9, and if I took a blue one away, it would be either 10 or 1. 
<img width="503" alt="image" src="https://github.com/user-attachments/assets/66fc62eb-cc81-4cbb-a79e-6de835870f1c">

This behavior is, indeed, happening, but at opposite ends, which makes sense since these are the lowest numbered kitten per addend. So that's likely a non-issue.
<img width="449" alt="image" src="https://github.com/user-attachments/assets/cad93a9f-02e2-4bec-a2de-fc154fbdf15c">

When I add one more blue kitten, the behavior described above shows this, which is a strange UI since it looks like #4 and #10 have switched places rather than adding another yellow. Ideally, the kittens would maintain their position and color, and any newly added kitten is randomly placed in the counting area.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/800f98ed-5891-4ca5-a8f0-5a17d03f2029">

Summarizing, if the kittens can keep their color attribute as is when adding new kittens, it would be less jarring for the user.

**Comment by marlitas** [comment]
Fixed above. Over to @catherinecarter for review.

**Comment by catherinecarter** [comment]
Looks good on the Sum screen (which this issue originally solely focused on). I changed the title to no longer focus only on screen 4, and instead be global so screens 2 and 3 can also be included.

Below are three screen shots where I switched scenes from 1 to 2 to 3 without touching or moving anything else. 

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/544d9e32-fcb0-4078-b047-8b5905c6b48a">
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/f6e93998-cf50-48b5-aa92-22c0edf70160">
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/8793957f-4d61-4962-802b-9ddf64a39d41">

Makes sense why this is happening - the new kitten is always the highest number.

**Comment by marlitas** [comment]
This should be addressed by the above commit. Over to @catherinecarter to review.

**Comment by marlitas** [comment]
Great. I believe we can close.
