### ISSUE TITLE
Bead improvements

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/number-pairs#39]
During the interviews, I noticed the beads don't touch, and that their starting position is very close to the center circle. 
<img width="209" alt="image" src="https://github.com/user-attachments/assets/fcf70937-1d56-4c21-a120-9eca2bbb85b1">

Acknowledging that I previously said being able to see the wire between the beads didn't bother me... I am changing my mind because the wire is now silver and it's more of a distraction.

Recommendations:
1. When the user shoves beads right next to each other or the organize button has been pressed, have the bead edges touch each other
2. Have the starting position of the beads be slightly farther from the separating knob. The dot is pretty big (which is fine), and therefore the space between the knob and the left/right beads currently is a little close. Increase the space between each bead closest to the knob and the knob to be at least one bead length (not much more, if at all)

**Comment by marlitas** [comment]
The closeness of the beads needs to be addressed in the artwork. There is space on both the left and right side of the svg, so in order for me to hide that in the code I would have to overlap the images which we have determined is not preferable.
Provided is close up of the left side of the blue bead svg I have.

<img width="62" alt="image" src="https://github.com/user-attachments/assets/3882cb14-2bb1-47ed-ba76-8d24022aa6f1">

The second note can be handled in the code. Thanks!

**Comment by catherinecarter** [comment]
Ah, thanks, @marlitas! I'll fix in the svg and send it on over.

**Comment by marlitas** [comment]
The above requests were added in. Over to @catherinecarter to review.

**Comment by catherinecarter** [comment]
Closing this issue as a new one has been opened: #48
