### ISSUE TITLE
Change organize button on beads to match other representations

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/number-pairs#42]
During interviews, students pressed the organize button for all of the representations showing the ten-frame but did not press the new organize button for the beads. 

Based on this, let's make the organize button look the same across all representations (except the number line where there's no organize button at all): 
<img width="154" alt="image" src="https://github.com/user-attachments/assets/d1a8e825-8dba-403a-abed-fcbea013253b">

**Comment by marlitas** [comment]
Changed above. I think this can be closed now.

**Comment by marlitas** [comment]
Okay... this can now be closed. yay!
