### ISSUE TITLE
PhET-iO instrumentation of Property<SpeechSynthesisVoice>.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-pairs#47]
Related to #22 ...

In NumberPairsPreferences, there are 2 Properties that are problematic for PhET-iO instrumentation:

```ts
  // Voice for the primary locale
  primaryVoiceProperty: new Property<SpeechSynthesisVoice | null>( null ),

  // Voice for the second locale
  secondVoiceProperty: new Property<SpeechSynthesisVoice | null>( null ),
```

These Properties would require something like `phetioValueType: NullableIO( SpeechSynthesisVoiceIO )`. But `SpeechSynthesisVoice` is part of the native JavaScript API, so we cannot create IOType `SpeechSynthesisVoiceIO`.

Since available voices vary from OS to OS, and device to device, these Properties don't seem appropriate to save in a wrapper. So I recommend that we not instrument these Properties.

**Comment by marlitas** [comment]
We discussed this in PhET-iO meeting and decided that the Property<SpeechSynthesisVoice> do not need to be instrumented. Closing.
