### ISSUE TITLE
Investigate ability to highlight specific words in RichText

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-pairs#5]
Number Pairs has a design request to color code specific words in a sentence (see image below). Due to translation expectations this needs to be done with one StringProperty passed through to RichText. Unfortunately, it is my understanding that RichText currently does not support a feature like this. We would like it to work similar to other RichText css support like so: `<span style="background-color: blue;">color</span>`

The only downside here is that we will have to dispose and rebuild this RichText element every time a translation or number changes. Annoying, but possible and allowing rich text to support dynamic changes like that seems completely out of scope.

<img width="460" alt="image" src="https://github.com/user-attachments/assets/591eda9c-a413-4555-accf-83bbf9527eab">

@jonathanolson do you have ideas around what kind of lift it would be to get something like this working?

**Comment by jonathanolson** [comment]
I'm putting the finishing touches on the discussed approach, should be able to commit soon. Demo:

<img width="824" alt="image" src="https://github.com/user-attachments/assets/5578d8e3-230c-4016-92b8-8cdc88886a0b">

Can be run locally with the [sandbox url](http://localhost/scenery/tests/sandbox.html?script=scene.addChild(%20new%20RichText(%20%27This%20is%20a%20test%20with%20%3Cblue%3Eblue%3C%2Fblue%3E%20text%20being%20%3Cblue%3Ewrapped%20in%20a%20blue%20color%20that%20should%20support%20line%20wrap%3C%2Fblue%3E.%20Text%20can%20also%20be%20%3Ctranslucent%3Emore%20transparent%3C%2Ftranslucent%3E%2C%20or%20can%20be%20%3Cblur%3Eblurred%3C%2Fblur%3E%20or%20have%20%3Cshadow%3Edrop%20shadow%3C%2Fshadow%3E.%20Tags%20can%20be%20%3Cblue%3Erepeated%20or%20%3Cblur%3Enested%3C%2Fblur%3E%3C%2Fblue%3E%27%2C%20%7B%0A%20%20lineWrap%3A%20300%2C%0A%20%20tags%3A%20%7B%0A%20%20%20%20blur%3A%20node%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20new%20Node(%20%7B%0A%20%20%20%20%20%20%20%20children%3A%20%5B%20node%20%5D%2C%0A%20%20%20%20%20%20%20%20filters%3A%20%5B%20new%20GaussianBlur(%201.5%20)%20%5D%0A%20%20%20%20%20%20%7D%20)%3B%0A%20%20%20%20%7D%2C%0A%20%20%20%20shadow%3A%20node%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20new%20Node(%20%7B%0A%20%20%20%20%20%20%20%20children%3A%20%5B%20node%20%5D%2C%0A%20%20%20%20%20%20%20%20filters%3A%20%5B%20new%20DropShadow(%20new%20Vector2(%202%2C%201%20)%2C%202%2C%20%27red%27%20)%20%5D%0A%20%20%20%20%20%20%7D%20)%3B%0A%20%20%20%20%7D%2C%0A%20%20%20%20translucent%3A%20node%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20new%20Node(%20%7B%0A%20%20%20%20%20%20%20%20children%3A%20%5B%20node%20%5D%2C%0A%20%20%20%20%20%20%20%20opacity%3A%200.5%0A%20%20%20%20%20%20%7D%20)%3B%0A%20%20%20%20%7D%2C%0A%20%20%20%20blue%3A%20node%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20new%20Node(%20%7B%0A%20%20%20%20%20%20%20%20children%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20Rectangle.bounds(%20node.bounds.dilated(%201%20)%2C%20%7B%20fill%3A%20%27%2388f%27%20%7D%20)%2C%0A%20%20%20%20%20%20%20%20%20%20node%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%20)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%20)%20)%3B)

**Comment by jonathanolson** [comment]
@marlitas can you try it out / review?

**Comment by marlitas** [comment]
Very cool! I can either tackle this later today, or once I get back on Thursday. Thanks!

**Comment by marlitas** [comment]
This is working really well.

I tried it out with NumberPairs and it is doing exactly what we want. I also played with it in sandbox to check on some edge cases, and it really seems to be handling everything well and as expected. The documentation is clear and the API is lovely. Thanks for the work here @jonathanolson! I think we're ready to close.
