### ISSUE TITLE
Export and implement sim artwork

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-pairs#7]
The sim is ready to start adding image assets in whenever design is ready to export. This issue is tracking any related work.

The only asset that we may want to draw in code are the cubes. However, since everything else will be an image asset, not sure wether keeping that consistent would be more worth it. Something to discuss.

**Comment by catherinecarter** [comment]
I believe this is ready to close? The artwork is in the assets folder in the shared drive. Closing.
